sriramveeraghanta/SOEN_6441_Project_G40

src/army/Unit.java, src/common/EnumClass.java, src/continent/Continent.java, src/country/Country.java, src/player/Player.java
added some base data classes for the Risk game(unit, country, continent,player) and enum defined types for unit type and player color.
=> added some base data classes for the Risk game

src/model/CountryModel.java, src/model/PlayerModel.java, src/model/UnitModel.java
=> Removed deleted files

src/model/CountryModel.java, src/model/GameModel.java, src/model/PlayerModel.java, src/resources/map_data.json, src/view/GameView.java
=> first pass for json

src/model/RiskMessages.java
Added a message class "RiskMessage.java" in model package
=> Added a message class 

.classpath, README.md, src/model/CountryModel.java, src/model/DeckModel.java, src/model/GameModel.java, src/model/PhaseStartUpModel.java, src/model/PlayerModel.java, src/model/UnitModel.java, src/view/GameView.java
Loading Countries, Players, and assigning countries to players by round
robin
=> Modified some classes added StartUp phase.

src/model/PhaseAttachModel.java
PhaseAttachModel.java added to Model package
=> PhaseAttachModel.java added to Model package

src/Game.java, src/models/CountryModel.java
* removed the  message in readme (#17)
* getting latest Version (#9)
* PhaseAttachModel.java added to Model package
* created GameBoardPanel class with phase action buttons (#16)
* Committing model classes
* Committing model classes
* Committing GameBordPanel class in View Package
* Committing Risk message class
* Committing GameBoardPanel class
* committing model classes
* class path
* classpath
* classpath file
* settings
* Update README.md
* git ignore updated and ignoring few settings files
* Update .classpath
* Update .classpath
* graph file added (#18)
* Add files via upload
graph file initial commit
* neighbor countries added
* adjacent country code is added
* JSON package build path configuration
* bugfixes and dependency issues fixed.
* Tweeking up few things and setting up JUnit …
=> getting Latest Version (#11)

src/controllers/GraphCheck.java, src/controllers/MapFileDataExtraction.java, src/controllers/StartUp.java, src/models/CountryModel.java, src/models/GameModel.java, src/models/PhaseAttachModel.java, src/views/GameView.java
- The files CountryModel.java , GameModel.java, GameView.java, GraphCheck.java, MapFileDataExtraction.java PhaseAttachModel.Java were
update by commenting the parts giving error so that I can run the
project.
- Deleted the PhaseStartUpModel.java
- Created the StartUp.java class to handle the loading phase of the game
=> Updated the StartUp Class

src/action/action.java, src/controllers/MapFileDataExtraction.java, src/utils/GameConstant.java, src/views/GameBoardMap.java, src/views/GameBoardSideBar.java
-Modified files in Views package for displaying phase action buttons and image.
-Created action listener in action.java file
-modified game constants
=> Modified files in view package 

src/controllers/AttackPhase.java, src/controllers/FortificationPhase.java, src/controllers/ReinforcementPhase.java, src/controllers/StartUp.java, src/models/CardModel.java, src/models/PlayerModel.java, src/utils/Common.java, src/utils/Countries.java
- modified model classes 
- mdified startUp phase
- added Attack phase
- added Reinforcement phase
- added Fortification phase
=> modified model classes and added logic to game phases

src/action/action.java, src/controllers/AttackPhase.java, src/controllers/FortificationPhase.java, src/controllers/MapFileDataExtraction.java, src/controllers/ReinforcementPhase.java, src/controllers/StartUp.java, src/models/CardModel.java, src/models/PlayerModel.java, src/utils/Common.java, src/utils/Countries.java, src/utils/GameConstant.java, src/views/GameBoardMap.java, src/views/GameBoardSideBar.java
* -Modified files in Views package for displaying phase action buttons and (#30)
image.
-Created actionlistener in action.java file
-modified game constants
* get latest version (#1)
* getting latest Version (#9)
* PhaseAttachModel.java added to Model package
* created GameBoardPanel class with phase action buttons (#16)
* Committing model classes
* Committing model classes
* Committing GameBordPanel class in View Package
* Committing Risk message class
* Committing GameBoardPanel class
* committing model classes
* class path
* classpath
* classpath file
* settings
* Update README.md
* get latest version (#10)
* removed the  message in readme (#17)
* getting latest Version (#9)
* PhaseAttachModel.java added to Model package
* created GameBoardPanel class with phase action buttons (#16)
* …
=> Get Latest Version (#14)

src/controllers/AttackPhase.java, src/controllers/ReinforcementPhase.java, src/controllers/StartUp.java, src/utils/Countries.java
update game logic in attack phase
=> update game logic in attack phase

src/Game.java, src/action/action.java, src/controllers/AttackPhase.java, src/controllers/MapBuilder.java, src/controllers/StartUp.java, src/models/GameModel.java, src/tests/TestMapFileDataExtraction.java, src/tests/TestPhaseControllers.java, src/views/GameBoardSideBar.java, src/views/GameBoardToolbar.java, src/views/GameView.java, src/views/HomeView.java
Fixed the Bugs to have a running master branch
=> Fixed the Bugs to have a running master branch

src/Game.java, src/RunMVC.java, src/action/SampleAction.java, src/controllers/SampleController.java, src/controllers/SampleHelperClass.java, src/models/SampleModel.java, src/views/SampleView.java
I have added a running Sample of MVC following the same structure we have in our project. all files start with Sample... except in the launcher.
Please follow this sample to fix the project.
=> I have added a running Sample of MVC

src/controllers/GameController.java, src/controllers/MapBuilder.java, src/models/ContinentModel.java, src/models/GameModel.java, src/tests/TestMapFileDataExtraction.java, src/utils/GameException.java
modified map builder added some validations
=> modified map builder added some validations

src/main/helpers/MapBuilder.java, src/main/utills/GameCommons.java
added the adjacent country validation
=> added the adjacent country validation

src/main/helpers/MapBuilder.java
=> fixed size bug

src/main/Main.java, src/main/controllers/GameController.java, src/main/helpers/MapBuilder.java
added the continent adjacency validation
=> added the continent adjacency validation

src/main/helpers/MapBuilder.java
applied validation to read map file which creates the continents and countries
=> Applied validation to read map file

resources/views/AttackDialogView.fxml, resources/views/GameBoard.fxml, src/main/controllers/AttackPhaseDialogController.java, src/main/controllers/GameBoardController.java, src/main/controllers/GameController.java, src/main/helpers/ReinforcementPhase.java
=> fixed reinforcement card bug

resources/views/AttackDialogView.fxml, resources/views/GameBoard.fxml, src/main/controllers/GameBoardController.java, src/main/helpers/ReinforcementPhase.java, src/main/models/GameModel.java, src/main/models/PlayerModel.java
added the next and current player
=> added the next and current player

src/main/controllers/GameBoardController.java, src/main/helpers/MapBuilder.java, src/main/helpers/ReinforcementPhase.java
=> fixed reinforcement bug

src/main/controllers/GameBoardController.java, src/main/helpers/AttackPhase.java, src/main/helpers/ReinforcementPhase.java
=> made access modifiers public

resources/views/AttackDialogView.fxml, src/main/controllers/AttackPhaseDialogController.java, src/main/helpers/AttackPhase.java
fixed some bugs in attack action
=> fixed some bugs in attack action
